[project]
name = "napari-tmidas"
dynamic = ["version"]
description = "A plugin for batch processing of confocal and whole-slide microscopy images of biological tissues"
readme = "README.md"
license = {file = "LICENSE"}
authors = [
  {name = "Marco Meer"},
  {email = "marco.meer@pm.me"},
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Framework :: napari",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Image Processing",
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.23.0,<2.0",
    "magicgui",
    "tqdm",
    "qtpy",
    "scikit-image>=0.19.0",
    "pyqt5",
    "zarr",
    "ome-zarr",
    "napari-ome-zarr",
    "torch>=1.12.0",
    "torchvision>=0.13.0",
    "timm",
    "opencv-python",
    "cmake",
    "nd2",
    "pylibCZIrw",
    "readlif",
    "tiffslide",
    "hydra-core",
    "eva-decord",
    "acquifer-napari",
]

[project.optional-dependencies]
testing = [
    "tox",
    "pytest>=7.0.0",
    "pytest-cov",
    "pytest-qt",
    "pytest-timeout",
    "napari",
    "pyqt5",
    "psygnal>=0.8.0",
]

[project.entry-points."napari.manifest"]
napari-tmidas = "napari_tmidas:napari.yaml"

[project.urls]
"Bug Tracker" = "https://github.com/macromeer/napari-tmidas/issues"
"Documentation" = "https://github.com/macromeer/napari-tmidas#README.md"
"Source Code" = "https://github.com/macromeer/napari-tmidas"
"User Support" = "https://github.com/macromeer/napari-tmidas/issues"

[build-system]
requires = ["setuptools>=42.0.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.yaml"]


[tool.setuptools_scm]
write_to = "src/napari_tmidas/_version.py"


[tool.black]
line-length = 79
target-version = ['py310']

[tool.ruff]
line-length = 79
lint.select = [
    "E", "F", "W", #flake8
    "UP", # pyupgrade
    "I", # isort
    "BLE", # flake8-blind-exception
    "B", # flake8-bugbear
    "A", # flake8-builtins
    "C4", # flake8-comprehensions
    "ISC", # flake8-implicit-str-concat
    "G", # flake8-logging-format
    "PIE", # flake8-pie
    "SIM", # flake8-simplify
]
lint.ignore = [
    "E501", # line too long. let black handle this
    "UP006", "UP007", # type annotation. As using magicgui require runtime type annotation then we disable this.
    "SIM117", # flake8-simplify - some of merged with statements are not looking great with black, reanble after drop python 3.9
]

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".mypy_cache",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "*vendored*",
    "*_vendor*",
]

target-version = "py38"
fix = true

[tool.pytest.ini_options]
# Limit test discovery to the package tests directory to avoid picking up
# helper scripts in repository root (e.g. duplicate test_registry.py) which
# caused import file mismatch errors on CI.
testpaths = [
    "src/napari_tmidas/_tests"
]
# Register custom markers used in the test suite.
markers = [
    "slow: marks tests as slow (deselect with '-m not slow')",
]
